In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [3]:
from sklearn.preprocessing import LabelEncoder
train.Item_Fat_Content=LabelEncoder().fit_transform(train.Item_Fat_Content)
train.Item_Type=LabelEncoder().fit_transform(train.Item_Type)
train.Outlet_Location_Type=LabelEncoder().fit_transform(train.Outlet_Location_Type)
train.Outlet_Type=LabelEncoder().fit_transform(train.Outlet_Type)
train.Outlet_Size=LabelEncoder().fit_transform(train.Outlet_Size)
train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,1,0.016047,4,249.8092,OUT049,1999,1,0,1,3735.1380
1,DRC01,5.92,2,0.019278,14,48.2692,OUT018,2009,1,2,2,443.4228
2,FDN15,17.50,1,0.016760,10,141.6180,OUT049,1999,1,0,1,2097.2700
3,FDX07,19.20,2,0.000000,6,182.0950,OUT010,1998,3,2,0,732.3800
4,NCD19,8.93,1,0.000000,9,53.8614,OUT013,1987,0,2,1,994.7052

In [4]:
model = LinearRegression()
from sklearn.model_selection import train_test_split
train,test = train_test_split(train, test_size=0.33, random_state=42)
test.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
7503,FDI28,14.300,1,0.026300,5,79.4302,OUT013,1987,0,2,1,1743.0644
2957,NCM17,7.930,1,0.071136,8,42.7086,OUT046,1997,2,0,1,356.8688
7031,FDC14,14.500,2,0.041313,3,42.0454,OUT049,1999,1,0,1,377.5086
1084,DRC36,NaN,2,0.044767,14,173.7054,OUT027,1985,1,2,3,5778.4782
856,FDS27,10.195,2,0.012456,10,197.5110,OUT035,2004,2,1,1,2356.9320

In [5]:
train.dropna(how='any',inplace=True,axis=1)
test.dropna(how='any',inplace=True,axis=1)
trainy=train['Item_Outlet_Sales']
testy=test['Item_Outlet_Sales']
trainx=train.drop(columns=['Item_Outlet_Sales','Outlet_Identifier','Item_Identifier'],axis=1)
testx=test.drop(columns=['Item_Outlet_Sales','Outlet_Identifier','Item_Identifier'],axis=1)

In [6]:
mdd=model.fit(trainx,trainy)

In [7]:
predict_test = model.predict(testx)

In [17]:
predict_test.shape

(2813,)

In [11]:
import numpy as np
Testy=np.array(testy)

In [18]:
Testy.shape

(2813,)

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(Testy,predict_test)

ValueError: continuous is not supported

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Type,Baking Goods,Breads,Breakfast,...,Soft Drinks,Starchy Foods,High,Medium,Small,LF,Low Fat,Regular,low fat,reg
0,9.30,0.016047,249.8092,OUT049,1999,Tier 1,Supermarket Type1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1,5.92,0.019278,48.2692,OUT018,2009,Tier 3,Supermarket Type2,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,17.50,0.016760,141.6180,OUT049,1999,Tier 1,Supermarket Type1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,19.20,0.000000,182.0950,OUT010,1998,Tier 3,Grocery Store,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,8.93,0.000000,53.8614,OUT013,1987,Tier 3,Supermarket Type1,0,0,0,...,0,0,1,0,0,0,1,0,0,0

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,...,OUT045,OUT046,OUT049,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,Tier 1,Tier 2,Tier 3
0,9.300,0.016047,249.8092,1999,0,0,0,0,1,0,...,0,0,1,0,1,0,0,1,0,0
1,5.920,0.019278,48.2692,2009,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,17.500,0.016760,141.6180,1999,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
3,19.200,0.000000,182.0950,1998,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,8.930,0.000000,53.8614,1987,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,0.056783,214.5218,1987,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
8519,8.380,0.046982,108.1570,2002,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
8520,10.600,0.035186,85.1224,2004,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
8521,7.210,0.145221,103.1332,2009,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
8522,14.800,0.044878,75.4670,1997,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

AttributeError: 'LinearRegression' object has no attribute 'coef_'

AttributeError: 'LinearRegression' object has no attribute 'intercept_'