In [79]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [80]:
train_data=pd.read_csv('train.csv')

In [81]:
print(train_data.head())

  Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047
1           DRC01         5.92          Regular         0.019278
2           FDN15        17.50          Low Fat         0.016760
3           FDX07        19.20          Regular         0.000000
4           NCD19         8.93          Low Fat         0.000000

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049
1            Soft Drinks   48.2692            OUT018
2                   Meat  141.6180            OUT049
3  Fruits and Vegetables  182.0950            OUT010
4              Household   53.8614            OUT013

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1
1                       2009      Medium               Tier 3
2                       1999      Medium               Tier 1
3                       1998         NaN               Tier 3
4                       1987        High               Tier 3

         Outlet_Type  Item_Outlet_Sales
0  Supermarket Type1          3735.1380
1  Supermarket Type2           443.4228
2  Supermarket Type1          2097.2700
3      Grocery Store           732.3800
4  Supermarket Type1           994.7052

In [82]:
train_y=train_data['Item_Outlet_Sales']
train_data=train_data.drop(columns=['Item_Outlet_Sales'],axis=1)

In [83]:
train_data=train_data.drop(columns=['Item_Identifier'],axis=1)

In [84]:
train_data['Item_Fat_Content'].replace(to_replace =['low fat','LF'], 
                 value ='Low Fat')

0       Low Fat
1       Regular
2       Low Fat
3       Regular
4       Low Fat
         ...
8518    Low Fat
8519    Regular
8520    Low Fat
8521    Regular
8522    Low Fat
Name: Item_Fat_Content, Length: 8523, dtype: object

In [85]:
train_data['Item_Fat_Content'].replace("reg", 
                 "Regular")

0       Low Fat
1       Regular
2       Low Fat
3       Regular
4       Low Fat
         ...
8518    Low Fat
8519    Regular
8520    Low Fat
8521    Regular
8522    Low Fat
Name: Item_Fat_Content, Length: 8523, dtype: object

In [86]:
IT=pd.get_dummies(train_data['Item_Type'])

In [87]:
OS=pd.get_dummies(train_data['Outlet_Size'])

In [88]:
IFC=pd.get_dummies(train_data['Item_Fat_Content'])

In [89]:
train_data=train_data.drop(columns=['Item_Type','Outlet_Size','Item_Fat_Content'])

In [90]:
result = pd.concat([train_data, IT], axis=1, sort=False)

In [91]:
result1 = pd.concat([result, OS], axis=1, sort=False)

In [92]:
result2= pd.concat([result1, IFC], axis=1, sort=False)

In [93]:
result2.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Location_Type,Outlet_Type,Baking Goods,Breads,Breakfast,...,Soft Drinks,Starchy Foods,High,Medium,Small,LF,Low Fat,Regular,low fat,reg
0,9.30,0.016047,249.8092,OUT049,1999,Tier 1,Supermarket Type1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
1,5.92,0.019278,48.2692,OUT018,2009,Tier 3,Supermarket Type2,0,0,0,...,1,0,0,1,0,0,0,1,0,0
2,17.50,0.016760,141.6180,OUT049,1999,Tier 1,Supermarket Type1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,19.20,0.000000,182.0950,OUT010,1998,Tier 3,Grocery Store,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4,8.93,0.000000,53.8614,OUT013,1987,Tier 3,Supermarket Type1,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [94]:
OI=pd.get_dummies(result2['Outlet_Identifier'])

In [95]:
OLT=pd.get_dummies(result2['Outlet_Location_Type'])

In [96]:
OT=pd.get_dummies(result2['Outlet_Type'])

In [97]:
rslt=result2.drop(columns=['Outlet_Identifier','Outlet_Location_Type','Outlet_Type'])

In [98]:
rslt= pd.concat([rslt, OI], axis=1, sort=False)

In [99]:
rslt= pd.concat([rslt, OT], axis=1, sort=False)

In [100]:
rslt= pd.concat([rslt, OLT], axis=1, sort=False)

In [102]:
train_x=rslt

In [103]:
model = LinearRegression()

In [108]:
train_x.dropna()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Baking Goods,Breads,Breakfast,Canned,Dairy,Frozen Foods,...,OUT045,OUT046,OUT049,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,Tier 1,Tier 2,Tier 3
0,9.300,0.016047,249.8092,1999,0,0,0,0,1,0,...,0,0,1,0,1,0,0,1,0,0
1,5.920,0.019278,48.2692,2009,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,17.500,0.016760,141.6180,1999,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
3,19.200,0.000000,182.0950,1998,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,8.930,0.000000,53.8614,1987,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,0.056783,214.5218,1987,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
8519,8.380,0.046982,108.1570,2002,1,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
8520,10.600,0.035186,85.1224,2004,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
8521,7.210,0.145221,103.1332,2009,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
8522,14.800,0.044878,75.4670,1997,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0

In [109]:
model.fit(train_x,train_y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [110]:
print('\nCoefficient of model :', model.coef_)

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [111]:
print('\nIntercept of model',model.intercept_)

AttributeError: 'LinearRegression' object has no attribute 'intercept_'